-- 注意不同版本的mysql建表语句不一样额
CREATE TABLE "t_user" (
  "ID" int(11) AUTO_INCREMENT,
  "NAME" varchar(200) NOT NULL COMMENT '名称',
  "AGE" int(5) NOT NULL COMMENT '年龄',
  "CREATE_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  "UPDATE_TIME" timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY ("ID")
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='用户表';

CREATE TABLE `t_user` (
  `ID` int(11) AUTO_INCREMENT,
  `NAME` varchar(200) NOT NULL COMMENT '名称',
  `AGE` int(5) NOT NULL COMMENT '年龄',
  -- `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='用户表';